2025-07-25 09:40:01 +0000 - dagster - DEBUG - __ASSET_JOB - 49b1d745-4f23-453b-ab4d-186a96cc6900 - 1090 - LOGS_CAPTURED - Started capturing logs in process (pid: 1090).
2025-07-25 09:40:01 +0000 - dagster - DEBUG - __ASSET_JOB - 49b1d745-4f23-453b-ab4d-186a96cc6900 - 1090 - load_postgres_data - STEP_START - Started execution of step "load_postgres_data".
2025-07-25 09:40:07 +0000 - dagster - ERROR - __ASSET_JOB - 49b1d745-4f23-453b-ab4d-186a96cc6900 - 1090 - load_postgres_data - STEP_FAILURE - Execution of step "load_postgres_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "load_postgres_data"::

dlt.pipeline.exceptions.PipelineStepFailed: Pipeline execution failed at `step=sync` with exception:

<class 'dlt.common.configuration.exceptions.ConfigFieldMissingException'>
Missing fields in configuration: ['database', 'username', 'host'] SnowflakeCredentials
	for field `database` the following (config providers, keys) were tried in order:
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__CREDENTIALS__DATABASE)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__CREDENTIALS__DATABASE)
		(secrets.toml, postgres_to_snowflake.destination.snowflake.credentials.database)
		(secrets.toml, postgres_to_snowflake.destination.credentials.database)
		(secrets.toml, postgres_to_snowflake.credentials.database)
		(config.toml, postgres_to_snowflake.destination.snowflake.credentials.database)
		(config.toml, postgres_to_snowflake.destination.credentials.database)
		(config.toml, postgres_to_snowflake.credentials.database)
		(Environment Variables, DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE)
		(Environment Variables, DESTINATION__CREDENTIALS__DATABASE)
		(Environment Variables, CREDENTIALS__DATABASE)
		(secrets.toml, destination.snowflake.credentials.database)
		(secrets.toml, destination.credentials.database)
		(secrets.toml, credentials.database)
		(config.toml, destination.snowflake.credentials.database)
		(config.toml, destination.credentials.database)
		(config.toml, credentials.database)
	for field `username` the following (config providers, keys) were tried in order:
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__SNOWFLAKE__CREDENTIALS__USERNAME)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__CREDENTIALS__USERNAME)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__CREDENTIALS__USERNAME)
		(secrets.toml, postgres_to_snowflake.destination.snowflake.credentials.username)
		(secrets.toml, postgres_to_snowflake.destination.credentials.username)
		(secrets.toml, postgres_to_snowflake.credentials.username)
		(config.toml, postgres_to_snowflake.destination.snowflake.credentials.username)
		(config.toml, postgres_to_snowflake.destination.credentials.username)
		(config.toml, postgres_to_snowflake.credentials.username)
		(Environment Variables, DESTINATION__SNOWFLAKE__CREDENTIALS__USERNAME)
		(Environment Variables, DESTINATION__CREDENTIALS__USERNAME)
		(Environment Variables, CREDENTIALS__USERNAME)
		(secrets.toml, destination.snowflake.credentials.username)
		(secrets.toml, destination.credentials.username)
		(secrets.toml, credentials.username)
		(config.toml, destination.snowflake.credentials.username)
		(config.toml, destination.credentials.username)
		(config.toml, credentials.username)
	for field `host` the following (config providers, keys) were tried in order:
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__SNOWFLAKE__CREDENTIALS__HOST)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__CREDENTIALS__HOST)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__CREDENTIALS__HOST)
		(secrets.toml, postgres_to_snowflake.destination.snowflake.credentials.host)
		(secrets.toml, postgres_to_snowflake.destination.credentials.host)
		(secrets.toml, postgres_to_snowflake.credentials.host)
		(config.toml, postgres_to_snowflake.destination.snowflake.credentials.host)
		(config.toml, postgres_to_snowflake.destination.credentials.host)
		(config.toml, postgres_to_snowflake.credentials.host)
		(Environment Variables, DESTINATION__SNOWFLAKE__CREDENTIALS__HOST)
		(Environment Variables, DESTINATION__CREDENTIALS__HOST)
		(Environment Variables, CREDENTIALS__HOST)
		(secrets.toml, destination.snowflake.credentials.host)
		(secrets.toml, destination.credentials.host)
		(secrets.toml, credentials.host)
		(config.toml, destination.snowflake.credentials.host)
		(config.toml, destination.credentials.host)
		(config.toml, credentials.host)

Provider `secrets.toml` loaded values from locations:
	- /app/.dlt/secrets.toml
	- /var/dlt/secrets.toml
Provider `config.toml` loaded values from locations:
	- /app/.dlt/config.toml
	- /var/dlt/config.toml

WARNING: Your run dir (/app) is different from directory of your pipeline script (/usr/local/lib/python3.11/site-packages/dagster).
If you keep `.dlt` folder with secret files in the same directory as your pipeline script but run your script or a dlt cli command from some other folder, secrets/configs will not be found.
Learn more: https://dlthub.com/docs/general-usage/credentials/


Stack Trace:
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/app/my_source/assets.py", line 23, in load_postgres_data
    load_info = pipeline.run(source, write_disposition="replace")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 231, in _wrap
    step_info = f(self, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 280, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 713, in run
    self._sync_destination(destination, staging, dataset_name)
  File "/usr/local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 185, in _wrap
    rv = f(self, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 882, in _sync_destination
    raise PipelineStepFailed(self, "sync", None, ex, None) from ex

The above exception was caused by the following exception:
dlt.common.configuration.exceptions.ConfigFieldMissingException: Missing fields in configuration: ['database', 'username', 'host'] SnowflakeCredentials
	for field `database` the following (config providers, keys) were tried in order:
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__CREDENTIALS__DATABASE)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__CREDENTIALS__DATABASE)
		(secrets.toml, postgres_to_snowflake.destination.snowflake.credentials.database)
		(secrets.toml, postgres_to_snowflake.destination.credentials.database)
		(secrets.toml, postgres_to_snowflake.credentials.database)
		(config.toml, postgres_to_snowflake.destination.snowflake.credentials.database)
		(config.toml, postgres_to_snowflake.destination.credentials.database)
		(config.toml, postgres_to_snowflake.credentials.database)
		(Environment Variables, DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE)
		(Environment Variables, DESTINATION__CREDENTIALS__DATABASE)
		(Environment Variables, CREDENTIALS__DATABASE)
		(secrets.toml, destination.snowflake.credentials.database)
		(secrets.toml, destination.credentials.database)
		(secrets.toml, credentials.database)
		(config.toml, destination.snowflake.credentials.database)
		(config.toml, destination.credentials.database)
		(config.toml, credentials.database)
	for field `username` the following (config providers, keys) were tried in order:
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__SNOWFLAKE__CREDENTIALS__USERNAME)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__CREDENTIALS__USERNAME)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__CREDENTIALS__USERNAME)
		(secrets.toml, postgres_to_snowflake.destination.snowflake.credentials.username)
		(secrets.toml, postgres_to_snowflake.destination.credentials.username)
		(secrets.toml, postgres_to_snowflake.credentials.username)
		(config.toml, postgres_to_snowflake.destination.snowflake.credentials.username)
		(config.toml, postgres_to_snowflake.destination.credentials.username)
		(config.toml, postgres_to_snowflake.credentials.username)
		(Environment Variables, DESTINATION__SNOWFLAKE__CREDENTIALS__USERNAME)
		(Environment Variables, DESTINATION__CREDENTIALS__USERNAME)
		(Environment Variables, CREDENTIALS__USERNAME)
		(secrets.toml, destination.snowflake.credentials.username)
		(secrets.toml, destination.credentials.username)
		(secrets.toml, credentials.username)
		(config.toml, destination.snowflake.credentials.username)
		(config.toml, destination.credentials.username)
		(config.toml, credentials.username)
	for field `host` the following (config providers, keys) were tried in order:
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__SNOWFLAKE__CREDENTIALS__HOST)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__DESTINATION__CREDENTIALS__HOST)
		(Environment Variables, POSTGRES_TO_SNOWFLAKE__CREDENTIALS__HOST)
		(secrets.toml, postgres_to_snowflake.destination.snowflake.credentials.host)
		(secrets.toml, postgres_to_snowflake.destination.credentials.host)
		(secrets.toml, postgres_to_snowflake.credentials.host)
		(config.toml, postgres_to_snowflake.destination.snowflake.credentials.host)
		(config.toml, postgres_to_snowflake.destination.credentials.host)
		(config.toml, postgres_to_snowflake.credentials.host)
		(Environment Variables, DESTINATION__SNOWFLAKE__CREDENTIALS__HOST)
		(Environment Variables, DESTINATION__CREDENTIALS__HOST)
		(Environment Variables, CREDENTIALS__HOST)
		(secrets.toml, destination.snowflake.credentials.host)
		(secrets.toml, destination.credentials.host)
		(secrets.toml, credentials.host)
		(config.toml, destination.snowflake.credentials.host)
		(config.toml, destination.credentials.host)
		(config.toml, credentials.host)

Provider `secrets.toml` loaded values from locations:
	- /app/.dlt/secrets.toml
	- /var/dlt/secrets.toml
Provider `config.toml` loaded values from locations:
	- /app/.dlt/config.toml
	- /var/dlt/config.toml

WARNING: Your run dir (/app) is different from directory of your pipeline script (/usr/local/lib/python3.11/site-packages/dagster).
If you keep `.dlt` folder with secret files in the same directory as your pipeline script but run your script or a dlt cli command from some other folder, secrets/configs will not be found.
Learn more: https://dlthub.com/docs/general-usage/credentials/


Stack Trace:
  File "/usr/local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 786, in _sync_destination
    remote_state = self._restore_state_from_destination()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 1589, in _restore_state_from_destination
    with self._get_destination_clients(schema)[0] as job_client:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 1337, in _get_destination_clients
    destination_client, staging_client = get_destination_clients(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/destinations/dataset/utils.py", line 85, in get_destination_clients
    client = destination.client(schema, initial_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/common/destination/reference.py", line 173, in client
    config = self.configuration(initial_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/common/destination/reference.py", line 160, in configuration
    config = resolve_configuration(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/common/configuration/resolve.py", line 75, in resolve_configuration
    return _resolve_configuration(config, sections, (), explicit_value, accept_partial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/common/configuration/resolve.py", line 181, in _resolve_configuration
    _resolve_config_fields(
  File "/usr/local/lib/python3.11/site-packages/dlt/common/configuration/resolve.py", line 302, in _resolve_config_fields
    current_value, traces = _resolve_config_field(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/common/configuration/resolve.py", line 415, in _resolve_config_field
    value = _resolve_configuration(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlt/common/configuration/resolve.py", line 181, in _resolve_configuration
    _resolve_config_fields(
  File "/usr/local/lib/python3.11/site-packages/dlt/common/configuration/resolve.py", line 329, in _resolve_config_fields
    raise ConfigFieldMissingException(type(config).__name__, unresolved_fields)

