[32m2025-07-24 11:30:12 +0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 958c485d-a09e-4d40-8c17-5b3a065b6f22 - 24111 - LOGS_CAPTURED - Started capturing logs in process (pid: 24111).
[32m2025-07-24 11:30:13 +0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 958c485d-a09e-4d40-8c17-5b3a065b6f22 - 24111 - postgres_to_snowflake - STEP_START - Started execution of step "postgres_to_snowflake".
[32m2025-07-24 11:30:13 +0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 958c485d-a09e-4d40-8c17-5b3a065b6f22 - 24111 - postgres_to_snowflake - STEP_FAILURE - Execution of step "postgres_to_snowflake" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "postgres_to_snowflake"::

ModuleNotFoundError: No module named 'psycopg2'

Stack Trace:
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/my_source/my-source/my_source/assets.py", line 10, in postgres_to_snowflake
    source = sql_database(credentials)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/dlt/extract/decorators.py", line 208, in __call__
    source = self._deco_f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/dlt/extract/decorators.py", line 304, in _wrap
    return _eval_rv(rv, schema_copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/dlt/extract/decorators.py", line 264, in _eval_rv
    _rv = list(_rv)
          ^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/dlt/sources/sql_database/__init__.py", line 111, in sql_database
    engine = engine_from_credentials(credentials)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/dlt/sources/sql_database/helpers.py", line 321, in engine_from_credentials
    engine = create_engine(credentials, **backend_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 602, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user6/Project Dagster with dlt/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 696, in import_dbapi
    import psycopg2
[0m
